import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use — Doctrinally.AI",
};

export default function TermsPage() {
  return (
    <div className="container mx-auto max-w-3xl px-4 py-16">
      <h1 className="font-heading text-4xl tracking-tight">Terms of Use</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: April 4, 2026
      </p>

      <div className="prose mt-10 max-w-none text-foreground prose-headings:font-heading prose-headings:tracking-tight prose-h2:mt-10 prose-h2:text-2xl prose-h3:mt-6 prose-h3:text-lg prose-p:leading-7 prose-p:text-muted-foreground prose-li:text-muted-foreground prose-strong:text-foreground">
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using Doctrinally.AI (the &quot;Service&quot;), you
          agree to be bound by these Terms of Use. If you are using the Service
          on behalf of a church or organization, you represent that you have the
          authority to bind that organization to these terms.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          Doctrinally.AI is an AI-powered chat platform for churches. The
          Service allows church administrators to upload sermons, documents, and
          other content, which is then indexed and made available through an AI
          chat interface for church members. The AI generates responses grounded
          in the church&apos;s uploaded content and the Bible.
        </p>

        <h2>3. Accounts and Registration</h2>
        <p>
          To use administrative features, you must create an account with
          accurate and complete information. You are responsible for maintaining
          the security of your account credentials. You must notify us
          immediately of any unauthorized use of your account.
        </p>

        <h2>4. Subscription and Billing</h2>

        <h3>Plans</h3>
        <p>
          The Service is offered under two subscription tiers: Standard
          ($49/month) and Enterprise ($99/month). Each plan includes specified
          limits for document uploads and messages per month.
        </p>

        <h3>Overage</h3>
        <p>
          Usage beyond included limits is billed at $0.25 per additional
          document upload and $0.25 per additional message. Overages are
          calculated at the end of each billing period.
        </p>

        <h3>Payment</h3>
        <p>
          All payments are processed through Stripe. Subscriptions renew
          automatically each month. You may cancel at any time through the
          billing settings.
        </p>

        <h3>Refunds</h3>
        <p>
          We do not offer refunds for partial months of service. If you cancel
          your subscription, you will continue to have access to the Service
          until the end of your current billing period.
        </p>

        <h2>5. Content and Intellectual Property</h2>

        <h3>Your Content</h3>
        <p>
          You retain ownership of all content you upload to the Service,
          including sermons, documents, videos, and other materials. By
          uploading content, you grant us a limited license to process, index,
          store, and use that content solely for the purpose of providing the
          Service.
        </p>

        <h3>AI-Generated Responses</h3>
        <p>
          Responses generated by the AI are provided for informational and
          educational purposes. While the AI is designed to ground its answers
          in your church&apos;s content and scripture, responses may not always
          be perfectly accurate. The Service is not a substitute for
          professional theological counsel.
        </p>

        <h3>Scripture</h3>
        <p>
          Bible passages displayed in the Service use the Berean Standard Bible
          (BSB) translation. The BSB text is used in accordance with its
          licensing terms.
        </p>

        <h2>6. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>
            Use the Service for any unlawful purpose or in violation of any
            applicable laws
          </li>
          <li>
            Upload content that infringes on intellectual property rights of
            others
          </li>
          <li>
            Attempt to access another church&apos;s data, content, or member
            information
          </li>
          <li>
            Interfere with or disrupt the Service or its underlying
            infrastructure
          </li>
          <li>
            Use automated tools to scrape, extract, or bulk-download content
            from the Service
          </li>
          <li>
            Misrepresent AI-generated responses as direct statements from church
            leadership
          </li>
        </ul>

        <h2>7. Church Isolation and Multi-Tenancy</h2>
        <p>
          Each church on the platform operates in an isolated environment. Your
          uploaded content, member data, and chat history are not accessible to
          other churches. We maintain strict data isolation between
          organizations.
        </p>

        <h2>8. Enterprise Features</h2>
        <p>
          Enterprise plan subscribers may use custom domains and custom branding.
          Custom domains require proper DNS configuration. We provision SSL
          certificates automatically through our hosting provider. You are
          responsible for maintaining your DNS records.
        </p>

        <h2>9. Availability and Support</h2>
        <p>
          We strive to maintain high availability of the Service but do not
          guarantee uninterrupted access. We may perform maintenance that
          temporarily affects availability. We will make reasonable efforts to
          notify you of planned maintenance in advance.
        </p>

        <h2>10. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, Doctrinally.AI shall not be
          liable for any indirect, incidental, special, consequential, or
          punitive damages arising from your use of the Service. Our total
          liability shall not exceed the amount paid by you in the twelve months
          preceding the claim.
        </p>

        <h2>11. Disclaimer of Warranties</h2>
        <p>
          The Service is provided &quot;as is&quot; and &quot;as
          available&quot; without warranties of any kind, either express or
          implied. We do not warrant that AI-generated responses will be
          accurate, complete, or suitable for any particular purpose.
        </p>

        <h2>12. Termination</h2>
        <p>
          We may suspend or terminate your access to the Service if you violate
          these terms. You may terminate your account at any time by canceling
          your subscription and contacting us. Upon termination, your data will
          be retained for 30 days before permanent deletion.
        </p>

        <h2>13. Changes to Terms</h2>
        <p>
          We may update these Terms of Use from time to time. We will notify you
          of material changes by posting the updated terms on our website.
          Continued use of the Service after changes constitutes acceptance of
          the revised terms.
        </p>

        <h2>14. Governing Law</h2>
        <p>
          These terms shall be governed by and construed in accordance with the
          laws of the United States, without regard to conflict of law
          provisions.
        </p>

        <h2>15. Contact Us</h2>
        <p>
          If you have questions about these Terms of Use, please contact us at{" "}
          <a href="mailto:legal@doctrinally.ai" className="text-primary">
            legal@doctrinally.ai
          </a>
          .
        </p>
      </div>
    </div>
  );
}
